// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: vod_upload_url.proto

package models

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type VodUrlUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"SpaceName"
	SpaceName string    `protobuf:"bytes,1,opt,name=SpaceName,proto3" json:"SpaceName"`       // 上传的空间
	URLSets   []*URLSet `protobuf:"bytes,2,rep,name=URLSets,proto3" json:"URLSets,omitempty"` // 设置每个URL的上传参数
}

func (x *VodUrlUploadRequest) Reset() {
	*x = VodUrlUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_upload_url_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VodUrlUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VodUrlUploadRequest) ProtoMessage() {}

func (x *VodUrlUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_upload_url_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VodUrlUploadRequest.ProtoReflect.Descriptor instead.
func (*VodUrlUploadRequest) Descriptor() ([]byte, []int) {
	return file_vod_upload_url_proto_rawDescGZIP(), []int{0}
}

func (x *VodUrlUploadRequest) GetSpaceName() string {
	if x != nil {
		return x.SpaceName
	}
	return ""
}

func (x *VodUrlUploadRequest) GetURLSets() []*URLSet {
	if x != nil {
		return x.URLSets
	}
	return nil
}

type URLSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceUrl    string `protobuf:"bytes,1,opt,name=SourceUrl,proto3" json:"SourceUrl,omitempty"`
	CallbackArgs string `protobuf:"bytes,2,opt,name=CallbackArgs,proto3" json:"CallbackArgs,omitempty"`
	Md5          string `protobuf:"bytes,3,opt,name=Md5,proto3" json:"Md5,omitempty"`
	TemplateId   string `protobuf:"bytes,4,opt,name=TemplateId,proto3" json:"TemplateId,omitempty"`
	Title        string `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Description  string `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	Tags         string `protobuf:"bytes,7,opt,name=Tags,proto3" json:"Tags,omitempty"`
	Category     string `protobuf:"bytes,8,opt,name=Category,proto3" json:"Category,omitempty"`
}

func (x *URLSet) Reset() {
	*x = URLSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_upload_url_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLSet) ProtoMessage() {}

func (x *URLSet) ProtoReflect() protoreflect.Message {
	mi := &file_vod_upload_url_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLSet.ProtoReflect.Descriptor instead.
func (*URLSet) Descriptor() ([]byte, []int) {
	return file_vod_upload_url_proto_rawDescGZIP(), []int{1}
}

func (x *URLSet) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *URLSet) GetCallbackArgs() string {
	if x != nil {
		return x.CallbackArgs
	}
	return ""
}

func (x *URLSet) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *URLSet) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *URLSet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *URLSet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *URLSet) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *URLSet) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_vod_upload_url_proto protoreflect.FileDescriptor

var file_vod_upload_url_proto_rawDesc = []byte{
	0x0a, 0x14, 0x76, 0x6f, 0x64, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x75, 0x72, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x6f, 0x64, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x13, 0x56, 0x6f, 0x64, 0x55, 0x72, 0x6c, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x55, 0x52,
	0x4c, 0x53, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x56, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x6f, 0x64, 0x2e,
	0x55, 0x52, 0x4c, 0x53, 0x65, 0x74, 0x52, 0x07, 0x55, 0x52, 0x4c, 0x53, 0x65, 0x74, 0x73, 0x22,
	0xe4, 0x01, 0x0a, 0x06, 0x55, 0x52, 0x4c, 0x53, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x4d, 0x64, 0x35, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x64, 0x35, 0x12, 0x1e,
	0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x3a, 0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x79,
	0x74, 0x65, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x42, 0x07, 0x56, 0x6f, 0x64, 0x50, 0x6c, 0x61, 0x79,
	0x50, 0x01, 0x5a, 0x08, 0x2e, 0x3b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0xa0, 0x01, 0x01, 0xd8,
	0x01, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vod_upload_url_proto_rawDescOnce sync.Once
	file_vod_upload_url_proto_rawDescData = file_vod_upload_url_proto_rawDesc
)

func file_vod_upload_url_proto_rawDescGZIP() []byte {
	file_vod_upload_url_proto_rawDescOnce.Do(func() {
		file_vod_upload_url_proto_rawDescData = protoimpl.X.CompressGZIP(file_vod_upload_url_proto_rawDescData)
	})
	return file_vod_upload_url_proto_rawDescData
}

var file_vod_upload_url_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vod_upload_url_proto_goTypes = []interface{}{
	(*VodUrlUploadRequest)(nil), // 0: Vcloud.Models.Vod.VodUrlUploadRequest
	(*URLSet)(nil),              // 1: Vcloud.Models.Vod.URLSet
}
var file_vod_upload_url_proto_depIdxs = []int32{
	1, // 0: Vcloud.Models.Vod.VodUrlUploadRequest.URLSets:type_name -> Vcloud.Models.Vod.URLSet
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vod_upload_url_proto_init() }
func file_vod_upload_url_proto_init() {
	if File_vod_upload_url_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_vod_upload_url_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VodUrlUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_upload_url_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vod_upload_url_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vod_upload_url_proto_goTypes,
		DependencyIndexes: file_vod_upload_url_proto_depIdxs,
		MessageInfos:      file_vod_upload_url_proto_msgTypes,
	}.Build()
	File_vod_upload_url_proto = out.File
	file_vod_upload_url_proto_rawDesc = nil
	file_vod_upload_url_proto_goTypes = nil
	file_vod_upload_url_proto_depIdxs = nil
}
