// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vod_upload.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *AbstractVodUrlUploadRequest) Validate() error {
	return nil
}
func (this *AbstractURLSet) Validate() error {
	return nil
}
func (this *ValuePair) Validate() error {
	return nil
}
func (this *QueryUploadTaskInfoResponse) Validate() error {
	if this.ResponseMetadata != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ResponseMetadata); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ResponseMetadata", err)
		}
	}
	if this.Result != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Result); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Result", err)
		}
	}
	return nil
}
func (this *QueryData) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *QueryUploadResult) Validate() error {
	for _, item := range this.VideoInfoList {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("VideoInfoList", err)
			}
		}
	}
	return nil
}
func (this *UploadVideoResponse) Validate() error {
	if this.ResponseMetadata != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ResponseMetadata); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ResponseMetadata", err)
		}
	}
	if this.Result != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Result); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Result", err)
		}
	}
	return nil
}
func (this *CommitData) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *CommitUploadInfoResponse) Validate() error {
	if this.SourceInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SourceInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SourceInfo", err)
		}
	}
	if this.Encryption != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Encryption); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Encryption", err)
		}
	}
	return nil
}
func (this *Encryption) Validate() error {
	return nil
}
func (this *URLSet) Validate() error {
	if this.SourceInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SourceInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SourceInfo", err)
		}
	}
	return nil
}
func (this *SourceInfo) Validate() error {
	return nil
}
func (this *VodUploadVideoRequest) Validate() error {
	return nil
}
